development:
  adapter: postgresql
  encoding: unicode
  database: pqp_development
  pool: 5
  username: gberger
  password: senha123

test:
  adapter: postgresql
  encoding: unicode
  database: pqp_test
  pool: 5
  username: gberger
  password: senha123

# production: Heroku